dist: bionic
language: rust

env:
  global:
    - CRATE_NAME=cadical-rs

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - rustup self update

script:
  - cargo build --verbose
  - cargo test -- --nocapture
  - cargo build --release --verbose
  - cargo test --release -- --nocapture

sudo: false

notifications:
  email: false
