[package]
name = "cadical"
version = "0.0.3"
authors = ["Miklos Maroti <mmaroti@gmail.com>"]
edition = "2018"
links = "ccadical"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
